spring.application.name=Notification Service
server.port=8083

spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

rabbitmq.exchange=booking.events
rabbitmq.queue=notification.queue
rabbitmq.routingkey=booking.confirmed

logging.level.com.smartticket.notification=INFO
